### ISSUE TITLE
Search Bar Update

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#36]
- [x] Search can be used for all subject and their id.
- [ ] #87
- [x] Lose the case sensitivity (?)
- [x] Restructure the code. Divide its function down into smaller function to diverse our options. Think of it like a constructor Search with multiple functions.
- [x] Combine search files or distinguish them in a clearer way.
- [x] Fix error: Search bar is not update on moving from page to page but only a reload (possible fix: using SearchBar vs NavigationBar).

**Comment by doggu** [comment]
TIL the search bar is not case sensitive but the editor panels become zero-height after typing for some reason so it only looked like no results were coming up; either way i've made it so that all whitespace is filtered out so that e.g. "csci2011" produces expected results

since this issue as well as the search bar not changing styles properly are a matter of styling, a fix for these issues will be included in https://github.com/chaunmt/Interactive-Prerequisite-Flowchart/issues/74 and brought back into the branch i will associate with this issue
