### ISSUE TITLE
Upload/Download json or image for user's personal graph

### ISSUE THREAD

**Issue by chaunmt** [chaunmt/Interactive-Prerequisite-Flowchart#40]
`Assign more works and deadlines`

**Comment by doggu** [comment]
Doing:
- [ ] JSON import/export
- [ ] "Open graph in new tab" button (since Ctrl+P produces a surprisingly usable graph)
- [ ] Clear button
- [ ] Incorporate new graph builder features (exclude, soft include, etc.)

hopefully most of these tasks are graphing-tool-agnostic, so i can build out the editor UI (even if mermaid is still regrettably center stage)

`Assign more works and deadlines`
